name: Tests

on:
  push:
    branches: [ develop, main ]
  pull_request:
    branches: [ main ]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    name: Run Tests
    strategy:
      matrix:
        node: [14.x, 16.x, 18.x]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: Install npm dependencies
        run: |
          npm ci
          # npm < 7 doesn't automatically install peers
          npm install -g npm-install-peers
          npm-install-peers

      - name: Lint code
        if: ${{ matrix.node == '18.x' }}
        run: npm run lint

      - name: Run tests
        run: npm run test
